<?= $this->extend('layouts/admin') ?>
<?= $this->section('content') ?>
<div class="d-flex flex-wrap align-items-end justify-content-between gap-3 mb-4"><div><h1 class="h4 mb-1">Ringkasan Layanan</h1><p class="muted mb-0">Kondisi ticket pada periode terpilih.</p></div><form class="d-flex gap-2 align-items-end"><div><label class="form-label small">Dari</label><input class="form-control" type="date" name="from" value="<?= esc($from) ?>"></div><div><label class="form-label small">Sampai</label><input class="form-control" type="date" name="to" value="<?= esc($to) ?>"></div><button class="btn btn-primary">Terapkan</button></form></div>
<div class="row g-3 mb-4"><div class="col-6 col-xl"><div class="card h-100"><div class="card-body d-flex align-items-center justify-content-between"><div><div class="muted small">Total Ticket</div><div class="metric"><?= esc($metrics['total']) ?></div></div><i class="bi bi-ticket fs-3 text-primary"></i></div></div></div><?php foreach ($metrics['statuses'] as $status): ?><div class="col-6 col-xl"><div class="card h-100"><div class="card-body d-flex align-items-center justify-content-between"><div><div class="muted small"><?= esc($status['name']) ?></div><div class="metric"><?= esc($status['total']) ?></div></div><span class="rounded-circle" style="width:12px;height:12px;background:<?= esc($status['color']) ?>"></span></div></div></div><?php endforeach ?></div>
<div class="row g-4"><div class="col-lg-8"><div class="card h-100"><div class="card-body"><h2 class="h6 mb-3">Tren Ticket Harian</h2><canvas id="trendChart" height="120"></canvas></div></div></div><div class="col-lg-4"><div class="card h-100"><div class="card-body"><h2 class="h6 mb-3">Ticket per Status</h2><canvas id="statusChart" height="200"></canvas></div></div></div><div class="col-lg-6"><div class="card"><div class="card-body"><h2 class="h6 mb-3">Ticket per Kategori</h2><canvas id="categoryChart" height="180"></canvas></div></div></div><div class="col-lg-6"><div class="card"><div class="card-body"><h2 class="h6 mb-3">Ticket per Prioritas</h2><canvas id="priorityChart" height="180"></canvas></div></div></div></div>
<?= $this->endSection() ?>
<?= $this->section('scripts') ?><script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script><script>
const metrics=<?= json_encode($metrics, JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?>;
new Chart(document.getElementById('trendChart'),{type:'line',data:{labels:metrics.trend.map(x=>x.day),datasets:[{label:'Ticket',data:metrics.trend.map(x=>Number(x.total)),borderColor:'#2563eb',backgroundColor:'rgba(37,99,235,.12)',fill:true,tension:.35}]},options:{responsive:true,plugins:{legend:{display:false}}}});
const makeBars=(id,rows)=>new Chart(document.getElementById(id),{type:'bar',data:{labels:rows.map(x=>x.name),datasets:[{data:rows.map(x=>Number(x.total)),backgroundColor:rows.map(x=>x.color||'#2563eb'),borderRadius:6}]},options:{responsive:true,plugins:{legend:{display:false}}}});
makeBars('statusChart',metrics.statuses);makeBars('categoryChart',metrics.categories);makeBars('priorityChart',metrics.priorities);
</script><?= $this->endSection() ?>
