<?= $this->extend('layouts/admin') ?>
<?= $this->section('content') ?>
<div class="d-flex justify-content-between align-items-start mb-4"><div><a class="text-decoration-none small" href="<?= site_url('admin/tickets') ?>"><i class="bi bi-arrow-left"></i> Kembali ke ticket</a><h1 class="h4 mt-2 mb-1"><?= esc($ticket['ticket_number']) ?></h1><p class="muted mb-0"><?= esc($ticket['subject']) ?></p></div><div class="d-flex gap-2"><span class="badge fs-6" style="background:<?= esc($ticket['priority_color']) ?>"><?= esc($ticket['priority_name']) ?></span><span class="badge fs-6" style="background:<?= esc($ticket['status_color']) ?>"><?= esc($ticket['status_name']) ?></span></div></div>
<div class="row g-4">
<div class="col-lg-8">
<div class="card mb-4"><div class="card-body"><div class="row g-3 mb-3"><div class="col-sm-4"><small class="muted">Pelapor</small><div class="fw-semibold"><?= esc($ticket['reporter_name']) ?></div><small><?= esc($ticket['whatsapp_number']) ?></small></div><div class="col-sm-4"><small class="muted">Kategori / Layanan</small><div class="fw-semibold"><?= esc($ticket['category_name']) ?></div><small><?= esc($ticket['service_name'] ?? 'Belum ditentukan') ?></small></div><div class="col-sm-4"><small class="muted">Dibuat</small><div class="fw-semibold"><?= esc($ticket['created_at']) ?></div><small>Channel: <?= esc($ticket['channel']) ?></small></div></div><hr><div class="text-break"><?= nl2br(esc($ticket['description'])) ?></div></div></div>
<div class="card mb-4"><div class="card-header bg-white fw-semibold">Percakapan</div><div class="card-body"><?php if ($messages === []): ?><p class="muted mb-0">Belum ada pesan.</p><?php else: foreach ($messages as $message): ?><div class="d-flex mb-3 <?= $message['direction'] === 'out' ? 'justify-content-end' : '' ?>"><div class="rounded-3 p-3 <?= $message['direction'] === 'out' ? 'bg-primary text-white' : 'bg-light' ?>" style="max-width:85%"><small class="<?= $message['direction'] === 'out' ? 'text-white-50' : 'muted' ?>"><?= esc(strtoupper($message['channel'])) ?> · <?= esc($message['created_at']) ?> · <?= esc($message['delivery_status']) ?></small><div class="mt-1 text-break"><?= nl2br(esc($message['body'])) ?></div></div></div><?php endforeach; endif ?>
<?php if ($canMessage): ?><form method="post" action="<?= site_url('admin/tickets/' . $ticket['id'] . '/messages') ?>" class="mt-3"><?= csrf_field() ?><label class="form-label" for="body">Balas pelapor melalui WhatsApp</label><textarea class="form-control mb-2" name="body" id="body" rows="3" required></textarea><button class="btn btn-primary btn-sm">Kirim ke antrean</button></form><?php endif ?></div></div>
<div class="card"><div class="card-header bg-white fw-semibold">Timeline Aktivitas</div><div class="card-body"><div class="list-group list-group-flush"><?php foreach ($activities as $activity): ?><div class="list-group-item px-0"><div class="fw-semibold"><?= esc($activity['description']) ?></div><small class="muted"><?= esc($activity['user_name'] ?: 'Sistem') ?> · <?= esc($activity['created_at']) ?></small></div><?php endforeach ?></div></div></div>
</div>
<div class="col-lg-4">
<div class="card mb-4"><div class="card-header bg-white fw-semibold">Pengelolaan Ticket</div><div class="card-body"><?php if ($canUpdate): ?><form method="post" action="<?= site_url('admin/tickets/' . $ticket['id']) ?>"><?= csrf_field() ?><label class="form-label">Subjek</label><input class="form-control mb-3" name="subject" value="<?= esc($ticket['subject']) ?>" required><label class="form-label">Deskripsi</label><textarea class="form-control mb-3" rows="4" name="description" required><?= esc($ticket['description']) ?></textarea>
<label class="form-label">Kategori</label><select class="form-select mb-3" name="category_id"><?php foreach ($formData['categories'] as $row): ?><option value="<?= $row['id'] ?>" <?= $row['id'] == $ticket['category_id'] ? 'selected' : '' ?>><?= esc($row['name']) ?></option><?php endforeach ?></select>
<label class="form-label">Layanan</label><select class="form-select mb-3" name="service_type_id"><option value="">Tidak ditentukan</option><?php foreach ($formData['services'] as $row): ?><option value="<?= $row['id'] ?>" data-category-id="<?= $row['category_id'] ?>" <?= $row['id'] == $ticket['service_type_id'] ? 'selected' : '' ?>><?= esc($row['name']) ?></option><?php endforeach ?></select>
<label class="form-label">Prioritas</label><select class="form-select mb-3" name="priority_id"><?php foreach ($formData['priorities'] as $row): ?><option value="<?= $row['id'] ?>" <?= $row['id'] == $ticket['priority_id'] ? 'selected' : '' ?>><?= esc($row['name']) ?></option><?php endforeach ?></select><button class="btn btn-outline-primary w-100">Simpan Perubahan</button></form>
<?php endif ?>
<?php if ($canChangeStatus): ?><hr><form method="post" action="<?= site_url('admin/tickets/' . $ticket['id'] . '/status') ?>"><?= csrf_field() ?><label class="form-label">Ubah status</label><div class="input-group"><select class="form-select" name="status_id" required><option value="">Pilih status berikutnya</option><?php foreach ($formData['statuses'] as $row): ?><option value="<?= $row['id'] ?>"><?= esc($row['name']) ?></option><?php endforeach ?></select><button class="btn btn-primary" <?= $formData['statuses'] === [] ? 'disabled' : '' ?>>Ubah</button></div></form><?php endif ?>
<?php if ($canAssign): ?><hr><form method="post" action="<?= site_url('admin/tickets/' . $ticket['id'] . '/assignment') ?>"><?= csrf_field() ?><label class="form-label">Operator</label><select class="form-select mb-2" name="assignee_user_id"><option value="">Belum di-assign</option><?php foreach ($formData['users'] as $row): ?><option value="<?= $row['id'] ?>" <?= $row['id'] == $ticket['assignee_user_id'] ? 'selected' : '' ?>><?= esc($row['name']) ?></option><?php endforeach ?></select><label class="form-label">Tim</label><select class="form-select mb-3" name="team_id"><option value="">Tidak ditentukan</option><?php foreach ($formData['teams'] as $row): ?><option value="<?= $row['id'] ?>" <?= $row['id'] == $ticket['team_id'] ? 'selected' : '' ?>><?= esc($row['name']) ?></option><?php endforeach ?></select><button class="btn btn-outline-secondary w-100">Simpan Assignment</button></form><?php endif ?>
</div></div></div></div>
<?= $this->endSection() ?>
<?= $this->section('scripts') ?><script>
const ticketCategory=document.querySelector('form[action="<?= site_url('admin/tickets/' . $ticket['id']) ?>"] [name="category_id"]');
const ticketService=document.querySelector('form[action="<?= site_url('admin/tickets/' . $ticket['id']) ?>"] [name="service_type_id"]');
if(ticketCategory&&ticketService){ticketCategory.addEventListener('change',()=>{for(const option of ticketService.options){if(!option.value)continue;option.hidden=option.dataset.categoryId!==ticketCategory.value;if(option.hidden&&option.selected)ticketService.value=''}});ticketCategory.dispatchEvent(new Event('change'))}
</script><?= $this->endSection() ?>
